import type { NextPage } from "next"
import { useSession } from "next-auth/react"
import Head from "next/head"
import Link from "next/link"
import { trpc } from "../utils/trpc"

type TechnologyCardProps = {
	name: string
	description: string
	documentation: string
}

const Home: NextPage = () => {
	const hello = trpc.useQuery(["example.hello", { text: "from tRPC" }])

	const { data: session, status } = useSession()

	const isLoading = status === "loading"

	if (isLoading) {
		return <div>Loading...</div>
	}

	if (!session && !isLoading) {
		return (
			<div>
				<Link href={"/api/auth/signin"}>
					<a>Sign in</a>
				</Link>
			</div>
		)
	}

	return (
		<>
			<Head>
				<title>Todo NextJS App</title>
				<meta name='description' content='Generated by create-t3-app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<main className='container mx-auto flex flex-col items-center justify-center min-h-screen p-4'>
				<h1 className='text-5xl md:text-[5rem] leading-normal font-extrabold text-gray-700'>
					Todo <span className='text-sky-400'>Next</span>
					<span className='text-yellow-300'>JS</span> App
				</h1>
				<div className='pt-6 text-2xl text-blue-500 flex justify-center items-center w-full'>
					{hello.data ? (
						<p>{hello.data.greeting}</p>
					) : (
						<p>Loading..</p>
					)}
				</div>
			</main>
		</>
	)
}

export default Home
